# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: trusty
sudo: false
warnings_are_errors: false

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - name: "tf-stable"
      env: TENSORFLOW_VERSION="1.13.1"
    - name: "tf-1.12.0"
      env: TENSORFLOW_VERSION="1.12.0"
    - name: "2.0.0-alpha0"
      env:
        - TENSORFLOW_VERSION="2.0.0-alpha0"
    - name: "nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
  allow_failures:
    - name: "2.0.0-alpha0"
      env:
        - TENSORFLOW_VERSION="2.0.0-alpha0"
    - name: "nightly"
      env:
        - TENSORFLOW_VERSION="nightly"

before_script:
  - sudo apt-get update
  - sudo apt-get install python3
  - python3 --version
  - pip install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - R -e 'tensorflow::install_tensorflow(version = Sys.getenv("TENSORFLOW_VERSION"))'
