# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: trusty
sudo: false
warnings_are_errors: false

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - name: "tf-stable"
      env: TENSORFLOW_VERSION="1.13.1"
    - name: "2.0-preview"
      env:
        - TENSORFLOW_VERSION="https://files.pythonhosted.org/packages/d2/56/a2ac9e67910dbaebb579c57d33484d0447b228079dd0b0d4ae6cc5cb8e7d/tf_nightly_2.0_preview-2.0.0.dev20190228-cp37-cp37m-manylinux1_x86_64.whl"
        - TENSORFLOW_PYTHON="/usr/bin/python3"
    - name: "nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TENSORFLOW_PYTHON="/usr/bin/python3"
  allow_failures:
    - name: "2.0-preview"
      env:
        - TENSORFLOW_VERSION="https://files.pythonhosted.org/packages/d2/56/a2ac9e67910dbaebb579c57d33484d0447b228079dd0b0d4ae6cc5cb8e7d/tf_nightly_2.0_preview-2.0.0.dev20190228-cp37-cp37m-manylinux1_x86_64.whl"
        - TENSORFLOW_PYTHON="/usr/bin/python3"
        - PYVER=3.4
    - name: "nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TENSORFLOW_PYTHON="/usr/bin/python3"
        - PYVER=3.4

before_script:
  - sudo apt-get update
  - sudo apt-get install python3
  - python3 --version
  - pip install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - R -e 'tensorflow::install_tensorflow(version = Sys.getenv("TENSORFLOW_VERSION"))'
